# SPDX-License-Identifier: GPL-3.0-or-later
# ClusterRole required for ServiceAccount TokenReview (used when AUTH_SA=true).
# TokenReview is a cluster-scoped resource and cannot be granted via a namespaced Role.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: fusion-weave-api-tokenreview
rules:
  - apiGroups: ["authentication.k8s.io"]
    resources: ["tokenreviews"]
    verbs: ["create"]
