{{- $api := .Values.api | default dict -}}
{{- $apiService := $api.service | default dict -}}
{{- $apiMonitoring := $api.monitoring | default dict -}}
{{- if $api.enabled }}
# SPDX-License-Identifier: GPL-3.0-or-later
apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-api
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "fusion-weave.labels" . | nindent 4 }}
spec:
  type: {{ $apiService.type }}
  selector:
    {{- include "fusion-weave.api.selectorLabels" . | nindent 4 }}
  ports:
    - name: http
      port: {{ $apiService.port }}
      targetPort: {{ $apiService.port }}
    {{- if $apiMonitoring.enabled }}
    - name: metrics
      port: {{ $apiMonitoring.metricsPort }}
      targetPort: {{ $apiMonitoring.metricsPort }}
    {{- end }}
{{- end }}
