{{- $api := .Values.api | default dict -}}
{{- if $api.enabled }}
# SPDX-License-Identifier: GPL-3.0-or-later
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ ($api.serviceAccount | default dict).name }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "fusion-weave.labels" . | nindent 4 }}
{{- end }}
