{{- $api := .Values.api | default dict -}}
{{- $apiAuth := $api.auth | default dict -}}
{{- $apiSA := $api.serviceAccount | default dict -}}
{{- if and $api.enabled $apiAuth.saAuthEnabled }}
# SPDX-License-Identifier: GPL-3.0-or-later
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ .Release.Name }}-api-tokenreview
  labels:
    {{- include "fusion-weave.labels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ .Release.Name }}-api-tokenreview
subjects:
  - kind: ServiceAccount
    name: {{ $apiSA.name }}
    namespace: {{ .Release.Namespace }}
{{- end }}
