{{- $api := .Values.api | default dict -}}
{{- $apiSA := $api.serviceAccount | default dict -}}
{{- if $api.enabled }}
# SPDX-License-Identifier: GPL-3.0-or-later
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ $apiSA.name }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "fusion-weave.labels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: {{ $apiSA.name }}
subjects:
  - kind: ServiceAccount
    name: {{ $apiSA.name }}
    namespace: {{ .Release.Namespace }}
{{- end }}
