{{- $backup := .Values.backup | default dict -}}
{{- $backupSA := $backup.serviceAccount | default dict -}}
{{- if $backup.enabled }}
# SPDX-License-Identifier: GPL-3.0-or-later
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ $backupSA.name }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "fusion-weave.labels" . | nindent 4 }}
{{- end }}
