# SPDX-License-Identifier: GPL-3.0-or-later
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Values.serviceAccount.name }}
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "fusion-weave.labels" . | nindent 4 }}
